# Generated by Django 5.0.2 on 2024-03-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_prouct_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prouct',
            new_name='Product',
        ),
    ]
